services:
  spider-mongo: 
    image: mongo:4.0
    container_name: spider-mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: kek
    volumes:
      - ./mongo-data:/data/db